---
- name: Monitor Httpd Service
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 5001

  rules:
    - name: Restart httpd when down
      condition: event.payload.service == "httpd" and event.payload.status == "down"
      action:
        run_job_template:
          name: "Remediation - Restart Httpd"
          organization: "Default"
          # This passes the host from the webhook to the Job Template
          job_args:
            limit: "{{ event.payload.host }}"
